[package]
name = "falconcore"
version = "0.1.0"
edition = "2021"

[dependencies]
# পরে যোগ করবো যেমন: clap, anyhow ইত্যাদি
[dependencies]
cranelift = "0.108"
cranelift-module = "0.108"
cranelift-object = "0.108"
cranelift-jit = "0.108"
